package com._wiedzmin3najlepszy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TrollNegotiation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Troll Name")
	private java.lang.String trollsName;
	@org.kie.api.definition.type.Label("Contact (Thaler) found")
	private java.lang.Boolean contactFound;
	@org.kie.api.definition.type.Label("Decision: kill trolls")
	private java.lang.Boolean killTrolls;
	public TrollNegotiation() {
	}

	public java.lang.String getTrollsName() {
		return this.trollsName;
	}

	public void setTrollsName(java.lang.String trollsName) {
		this.trollsName = trollsName;
	}

	public java.lang.Boolean getContactFound() {
		return this.contactFound;
	}

	public void setContactFound(java.lang.Boolean contactFound) {
		this.contactFound = contactFound;
	}

	public java.lang.Boolean getKillTrolls() {
		return this.killTrolls;
	}

	public void setKillTrolls(java.lang.Boolean killTrolls) {
		this.killTrolls = killTrolls;
	}

	public TrollNegotiation(java.lang.String trollsName,
			java.lang.Boolean contactFound, java.lang.Boolean killTrolls) {
		this.trollsName = trollsName;
		this.contactFound = contactFound;
		this.killTrolls = killTrolls;
	}

}