package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Chat implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "AnswerToTheQuestion")
	private java.lang.String answer;

	public Chat() {
	}

	public java.lang.String getAnswer() {
		return this.answer;
	}

	public void setAnswer(java.lang.String answer) {
		this.answer = answer;
	}

	public Chat(java.lang.String answer) {
		this.answer = answer;
	}

}