package com._wiedzmin3najlepszy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class QuestActor implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Role")
	private java.lang.String role;

	public QuestActor() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public QuestActor(java.lang.String name, java.lang.String role) {
		this.name = name;
		this.role = role;
	}

}