package com._wiedzmin3najlepszy;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WagonInvestigation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Tracks found")
	private java.lang.Boolean tracksFound;
	@org.kie.api.definition.type.Label("Shoes trail found")
	private java.lang.Boolean shoesTrail;
	public WagonInvestigation() {
	}

	public java.lang.Boolean getTracksFound() {
		return this.tracksFound;
	}

	public void setTracksFound(java.lang.Boolean tracksFound) {
		this.tracksFound = tracksFound;
	}

	public java.lang.Boolean getShoesTrail() {
		return this.shoesTrail;
	}

	public void setShoesTrail(java.lang.Boolean shoesTrail) {
		this.shoesTrail = shoesTrail;
	}

	public WagonInvestigation(java.lang.Boolean tracksFound,
			java.lang.Boolean shoesTrail) {
		this.tracksFound = tracksFound;
		this.shoesTrail = shoesTrail;
	}

}